insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Conant Pitcock', 'Solnechnogorsk', 'Hobbies', 61, '$37571.03', 1);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Teriann Frany', 'Lagoa Seca', 'Sports', 91, '$2495.02', 2);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Nancee Pagitt', 'Hukeng', 'Reading', 50, '$8588.51', 3);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Noelle Gurery', 'Zongjia', 'Sports', 25, '$43618.69', 4);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Charo Surgen', 'Łomazy', 'Reading', 21, '$40466.65', 5);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Gwenni Debell', 'Krikil', 'Hobbies', 76, '$36925.13', 6);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Barnett Faloon', 'Qukou', 'Fashion', 24, '$44586.89', 7);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Maribel Doghartie', 'Cerava', 'Poetry', 68, '$5782.60', 8);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Jarrod Caulcott', 'Wamba', 'Reading', 25, '$49783.10', 9);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Welbie Fenton', 'Pniewy', 'Health', 20, '$35117.55', 10);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Joni Dresser', 'Yangshuo', 'Reading', 34, '$47100.30', 11);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Rudie Fone', 'Tiebiancheng', 'Poetry', 90, '$44589.56', 12);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Sauncho Borrill', 'La Garde', 'Hobbies', 100, '$38214.80', 13);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Rog Youdell', 'Tripoli', 'Fashion', 24, '$3488.11', 14);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Deeanne Steventon', 'Saba Yoi', 'Hobbies', 70, '$49593.58', 15);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Mendel Capewell', 'Madruga', 'Poetry', 55, '$18381.09', 16);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Baudoin Sucre', 'Huilong', 'Sports', 100, '$44588.93', 17);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Tailor Oakley', 'Khoa', 'Poetry', 39, '$4077.34', 18);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Constantine Slessor', 'Tacoma', 'Health', 25, '$39325.30', 19);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Katy Germon', 'Dłutów', 'Reading', 22, '$29062.21', 20);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Seth Woodruffe', 'Nice', 'Art', 44, '$32407.98', 21);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Sheelah Hobden', 'Kyriáki', 'Health', 41, '$2120.49', 22);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Jannelle Brambley', 'Örebro', 'Reading', 80, '$24915.01', 23);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Bellina Ren', 'Fiais da Beira', 'Sports', 65, '$5070.29', 24);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Clifford Ridde', 'Virovitica', 'Health', 26, '$12846.68', 25);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Colan Manby', 'San Carlos de Bariloche', 'Fashion', 70, '$45953.82', 26);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Herta Thewlis', 'Las Matas de Farfán', 'Health', 100, '$39936.89', 27);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Jacquelyn Paroni', 'Gunajaya', 'Poetry', 70, '$32840.01', 28);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Wainwright Pyle', 'Kambatatamakawu', 'Hobbies', 38, '$12801.74', 29);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Kirstyn Polak', 'Awayan', 'Sports', 28, '$15709.56', 30);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Lazaro Lumsdall', 'Kimanuit', 'Memes', 49, '$29789.63', 31);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Etheline Morecombe', 'Baishi', 'Art', 57, '$36050.26', 32);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Drew Antos', 'Nuevo Berlín', 'Fashion', 83, '$37396.43', 33);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Nonnah D''Oyly', 'Shuicha', 'Health', 79, '$46187.76', 34);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Zerk Aliberti', 'Linshi', 'Fashion', 21, '$34416.96', 35);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Jorey Kaes', 'Ust’ye', 'Fashion', 44, '$17628.09', 36);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Olin Haily', 'Hongde', 'Memes', 79, '$15.49', 37);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Buddie Cheltnam', 'Chaiwan', 'Hobbies', 94, '$18539.79', 38);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Ofella Yakobowitch', 'Jinotega', 'Hobbies', 42, '$26307.48', 39);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Cleavland Kynoch', 'Qo’ng’irot Shahri', 'Memes', 92, '$25510.76', 40);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Yevette Porker', 'San José del Guaviare', 'Memes', 83, '$29298.42', 41);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Ivonne Auty', 'Wuping', 'Reading', 60, '$47878.93', 42);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Roxine Mildmott', 'Shanglian', 'Hobbies', 46, '$12859.99', 43);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Barb Beade', 'Beloyarskiy', 'Hobbies', 76, '$25994.86', 44);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Guinevere Blankau', 'Guacamaya', 'Health', 62, '$9723.86', 45);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Morton Barkway', 'Ocho Rios', 'Fashion', 56, '$7541.25', 46);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Agna Hamill', 'Yeysk', 'Poetry', 91, '$17915.47', 47);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Aluin Franceschelli', 'Wolofeo', 'Poetry', 34, '$37376.10', 48);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Gerhardt Massot', 'Arsen’yev', 'Hobbies', 40, '$46892.09', 49);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Harwell MacKereth', 'Cabrobó', 'Reading', 35, '$20243.50', 50);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Broddy Whittlesee', 'Stockholm', 'Poetry', 60, '$27088.93', 51);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Beatriz Preist', 'Panggung', 'Reading', 68, '$2597.46', 52);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Feliza Pingston', 'Miringa', 'Hobbies', 40, '$32911.22', 53);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Alard Golley', 'Realeza', 'Hobbies', 18, '$20981.88', 54);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Brant Hilbourne', 'Sofiyivka', 'Hobbies', 80, '$22213.14', 55);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Robinia Gianullo', 'Karanganyarkrajan', 'Art', 57, '$49929.03', 56);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Rurik Broader', 'Lupo', 'Hobbies', 47, '$35380.99', 57);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Reggy Abrahamovitz', 'Narowlya', 'Reading', 22, '$47962.08', 58);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Herschel Rodliff', 'Vienne', 'Fashion', 72, '$36778.19', 59);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Carmel Mellem', 'Lamakera Dua', 'Hobbies', 57, '$16652.25', 60);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Kinnie Ivashechkin', 'Huangtang', 'Fashion', 38, '$18515.91', 61);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Noe Ammer', 'Sam Khok', 'Fashion', 21, '$28294.67', 62);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Skipper Le land', 'Campo Quijano', 'Sports', 61, '$30422.45', 63);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Ofelia Rabat', 'Fuenlabrada', 'Memes', 72, '$8856.92', 64);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Elsie Eddowis', 'Iracemápolis', 'Memes', 88, '$34552.07', 65);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Mary Wint', 'Buenlag', 'Poetry', 89, '$41434.89', 66);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Mendie Hosier', 'Kebonan', 'Reading', 64, '$15797.44', 67);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Fletcher Cuttelar', 'Xingyuan', 'Poetry', 72, '$28640.65', 68);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Lillian Geekie', 'Kaiyun', 'Memes', 51, '$22374.18', 69);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Silvester Cape', 'Winston Salem', 'Art', 50, '$48021.02', 70);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Kermy Grcic', 'Kuala Lumpur', 'Memes', 37, '$2985.13', 71);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Ollie McFie', 'Asino', 'Hobbies', 74, '$19384.84', 72);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Cthrine Joynson', 'Baryshevo', 'Sports', 99, '$17865.88', 73);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Darwin MacAllester', 'Kandete', 'Hobbies', 69, '$12818.27', 74);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Rodge Rasch', 'Otoka', 'Memes', 29, '$38785.26', 75);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Ax Leedal', 'Dongshi', 'Poetry', 91, '$29937.22', 76);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Michaella Darley', 'Abiko', 'Fashion', 50, '$22983.83', 77);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Davida Sutliff', 'Jiantian', 'Poetry', 29, '$32481.18', 78);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Aubree Gierhard', 'Netrakona', 'Hobbies', 92, '$2669.35', 79);
insert into Audiences (name, location, interest, age_range, budget, audience_id) values ('Pet Carlisle', 'Duzhenwan', 'Health', 90, '$34992.52', 80);
