insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (1, 1, 751, 'ice cream', 'Needs Work', 'Breakfast', '9/29/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (2, 2, 1191, 'pasta', 'Great', 'Dinner', '11/30/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (3, 3, 315, 'pasta', 'Okay', 'Lunch', '2/13/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (4, 4, 692, 'ice cream', 'Okay', 'Dinner', '12/1/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (5, 5, 874, 'chocolate', 'Okay', 'Dinner', '8/9/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (6, 6, 515, 'carrots', 'Needs Work', 'Breakfast', '3/7/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (7, 7, 507, 'chocolate', 'Great', 'Dinner', '3/23/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (8, 8, 958, 'ice cream', 'Great', 'Lunch', '7/30/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (9, 9, 1024, 'apples', 'Okay', 'Dinner', '9/16/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (10, 10, 236, 'chocolate', 'Great', 'Lunch', '8/5/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (11, 11, 1064, 'apples', 'Needs Work', 'Lunch', '8/14/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (12, 12, 872, 'bananas', 'Okay', 'Breakfast', '11/22/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (13, 13, 886, 'chocolate', 'Great', 'Dinner', '2/15/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (14, 14, 1043, 'apples', 'Great', 'Breakfast', '10/4/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (15, 15, 669, 'pasta', 'Needs Work', 'Dinner', '8/19/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (16, 16, 1164, 'pasta', 'Great', 'Breakfast', '10/3/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (17, 17, 951, 'pasta', 'Great', 'Breakfast', '11/2/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (18, 18, 977, 'pasta', 'Okay', 'Lunch', '2/13/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (19, 19, 386, 'pasta', 'Great', 'Dinner', '7/3/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (20, 20, 1038, 'pizza', 'Needs Work', 'Breakfast', '4/18/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (21, 21, 546, 'pizza', 'Needs Work', 'Lunch', '3/25/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (22, 22, 398, 'apples', 'Great', 'Dinner', '10/7/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (23, 23, 362, 'bananas', 'Needs Work', 'Dinner', '9/4/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (24, 24, 729, 'pasta', 'Needs Work', 'Lunch', '6/30/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (25, 25, 696, 'chocolate', 'Okay', 'Breakfast', '6/5/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (26, 26, 895, 'chocolate', 'Great', 'Breakfast', '10/1/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (27, 27, 264, 'pasta', 'Great', 'Breakfast', '9/7/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (28, 28, 1059, 'pasta', 'Okay', 'Dinner', '3/31/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (29, 29, 1182, 'carrots', 'Okay', 'Lunch', '4/22/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (30, 30, 1154, 'pasta', 'Okay', 'Dinner', '12/11/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (31, 31, 422, 'apples', 'Great', 'Lunch', '7/29/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (32, 32, 216, 'chocolate', 'Great', 'Lunch', '8/17/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (33, 33, 828, 'pizza', 'Needs Work', 'Lunch', '5/15/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (34, 34, 328, 'carrots', 'Okay', 'Lunch', '4/20/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (35, 35, 826, 'apples', 'Okay', 'Breakfast', '1/3/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (36, 36, 353, 'pasta', 'Okay', 'Breakfast', '2/5/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (37, 37, 763, 'carrots', 'Okay', 'Breakfast', '6/19/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (38, 38, 1193, 'pasta', 'Great', 'Lunch', '5/7/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (39, 39, 1099, 'ice cream', 'Okay', 'Lunch', '9/1/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (40, 40, 878, 'pizza', 'Great', 'Lunch', '3/18/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (41, 41, 1194, 'bananas', 'Needs Work', 'Breakfast', '5/8/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (42, 42, 504, 'chocolate', 'Okay', 'Dinner', '2/11/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (43, 43, 948, 'ice cream', 'Great', 'Dinner', '2/6/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (44, 44, 956, 'carrots', 'Needs Work', 'Lunch', '8/8/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (45, 45, 790, 'pizza', 'Great', 'Breakfast', '2/15/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (46, 46, 338, 'chocolate', 'Okay', 'Dinner', '4/29/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (47, 47, 275, 'bananas', 'Okay', 'Breakfast', '6/19/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (48, 48, 561, 'pizza', 'Needs Work', 'Dinner', '12/22/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (49, 49, 665, 'pizza', 'Needs Work', 'Lunch', '7/8/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (50, 50, 753, 'ice cream', 'Great', 'Breakfast', '6/2/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (51, 51, 402, 'chocolate', 'Needs Work', 'Breakfast', '3/1/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (52, 52, 414, 'pasta', 'Okay', 'Dinner', '8/23/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (53, 53, 698, 'pasta', 'Okay', 'Breakfast', '7/20/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (54, 54, 1075, 'carrots', 'Great', 'Lunch', '2/23/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (55, 55, 540, 'bananas', 'Needs Work', 'Dinner', '6/19/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (56, 56, 742, 'ice cream', 'Great', 'Breakfast', '11/17/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (57, 57, 1174, 'chocolate', 'Needs Work', 'Lunch', '12/18/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (58, 58, 954, 'carrots', 'Great', 'Dinner', '4/22/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (59, 59, 732, 'carrots', 'Great', 'Lunch', '5/12/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (60, 60, 955, 'carrots', 'Great', 'Lunch', '2/14/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (61, 61, 1087, 'pizza', 'Okay', 'Dinner', '6/29/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (62, 62, 743, 'pizza', 'Great', 'Lunch', '2/1/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (63, 63, 321, 'pasta', 'Okay', 'Lunch', '11/11/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (64, 64, 346, 'pasta', 'Okay', 'Breakfast', '11/9/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (65, 65, 295, 'ice cream', 'Great', 'Lunch', '9/7/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (66, 66, 338, 'pasta', 'Okay', 'Breakfast', '1/24/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (67, 67, 689, 'pizza', 'Okay', 'Dinner', '7/16/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (68, 68, 257, 'pasta', 'Needs Work', 'Lunch', '10/17/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (69, 69, 600, 'bananas', 'Great', 'Breakfast', '12/5/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (70, 70, 796, 'carrots', 'Great', 'Lunch', '9/9/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (71, 71, 321, 'chocolate', 'Great', 'Lunch', '8/12/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (72, 72, 1008, 'bananas', 'Great', 'Dinner', '9/21/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (73, 73, 500, 'ice cream', 'Great', 'Breakfast', '12/22/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (74, 74, 1030, 'ice cream', 'Okay', 'Breakfast', '10/19/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (75, 75, 963, 'carrots', 'Great', 'Lunch', '2/24/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (76, 76, 283, 'pasta', 'Okay', 'Lunch', '7/17/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (77, 77, 626, 'chocolate', 'Great', 'Lunch', '2/25/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (78, 78, 1007, 'chocolate', 'Needs Work', 'Breakfast', '11/10/2023');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (79, 79, 1084, 'ice cream', 'Great', 'Lunch', '2/4/2024');
insert into Food_Log (food_log_id, client_id, calories, food_items, comments, meal_type, dates) values (80, 80, 319, 'chocolate', 'Okay', 'Dinner', '1/25/2024');
