insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (1, '6/10/2024', 'pasta', 'dinner', 1, 'and certain vitamins and minerals', '5/17/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (2, '4/26/2024', 'carrots', 'lunch', 2, 'trans fat', '12/16/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (3, '4/28/2024', 'chocolate', 'snack', 3, 'total sugars', '1/30/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (4, '11/13/2023', 'ice cream', 'breakfast', 4, 'dietary fiber', '8/6/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (5, '4/30/2024', 'apples', 'snack', 5, 'saturated fat', '3/1/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (6, '8/8/2024', 'pizza', 'snack', 6, 'dietary fiber', '3/9/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (7, '2/6/2024', 'bananas', 'lunch', 7, 'sodium', '8/10/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (8, '10/9/2023', 'pizza', 'breakfast', 8, 'added sugars', '3/19/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (9, '2/29/2024', 'pasta', 'dinner', 9, 'trans fat', '5/9/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (10, '8/3/2024', 'carrots', 'dinner', 10, 'cholesterol', '7/18/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (11, '8/27/2023', 'carrots', 'snack', 11, 'total carbohydrate', '12/10/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (12, '8/28/2024', 'pizza', 'lunch', 12, 'added sugars', '8/21/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (13, '7/28/2024', 'apples', 'breakfast', 13, 'fat', '6/7/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (14, '2/25/2024', 'apples', 'breakfast', 14, 'added sugars', '8/5/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (15, '6/26/2024', 'chocolate', 'lunch', 15, 'and certain vitamins and minerals', '8/19/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (16, '9/19/2023', 'apples', 'breakfast', 16, 'protein', '7/13/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (17, '10/30/2023', 'ice cream', 'dinner', 17, 'saturated fat', '12/9/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (18, '12/15/2023', 'carrots', 'lunch', 18, 'protein', '6/4/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (19, '11/15/2023', 'bananas', 'dinner', 19, 'saturated fat', '9/29/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (20, '9/25/2023', 'chocolate', 'dinner', 20, 'trans fat', '2/22/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (21, '1/19/2024', 'carrots', 'breakfast', 21, 'added sugars', '7/20/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (22, '10/22/2023', 'bananas', 'lunch', 22, 'fat', '1/24/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (23, '11/21/2023', 'pasta', 'dinner', 23, 'total carbohydrate', '8/10/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (24, '6/30/2024', 'ice cream', 'dinner', 24, 'total sugars', '9/15/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (25, '9/6/2023', 'apples', 'dinner', 25, 'trans fat', '3/13/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (26, '12/22/2023', 'pizza', 'dinner', 26, 'total carbohydrate', '12/23/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (27, '8/5/2023', 'pasta', 'lunch', 27, 'added sugars', '11/24/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (28, '1/26/2024', 'apples', 'snack', 28, 'saturated fat', '9/13/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (29, '8/6/2024', 'apples', 'lunch', 29, 'fat', '9/30/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (30, '2/8/2024', 'apples', 'breakfast', 30, 'dietary fiber', '12/26/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (31, '2/1/2024', 'chocolate', 'lunch', 31, 'trans fat', '4/19/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (32, '11/3/2023', 'pasta', 'dinner', 32, 'dietary fiber', '1/13/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (33, '8/28/2023', 'carrots', 'dinner', 33, 'cholesterol', '7/7/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (34, '3/9/2024', 'carrots', 'breakfast', 34, 'total sugars', '8/6/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (35, '10/19/2023', 'chocolate', 'snack', 35, 'protein', '9/26/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (36, '3/25/2024', 'apples', 'dinner', 36, 'saturated fat', '12/15/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (37, '8/30/2023', 'ice cream', 'breakfast', 37, 'trans fat', '11/27/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (38, '3/1/2024', 'ice cream', 'dinner', 38, 'cholesterol', '2/22/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (39, '6/30/2024', 'apples', 'breakfast', 39, 'total sugars', '2/27/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (40, '4/10/2024', 'carrots', 'lunch', 40, 'added sugars', '7/12/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (41, '2/14/2024', 'carrots', 'dinner', 41, 'dietary fiber', '4/26/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (42, '4/6/2024', 'pizza', 'lunch', 42, 'sodium', '10/10/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (43, '1/11/2024', 'apples', 'snack', 43, 'total sugars', '4/20/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (44, '10/1/2023', 'pizza', 'snack', 44, 'total sugars', '9/20/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (45, '6/25/2024', 'carrots', 'breakfast', 45, 'added sugars', '2/8/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (46, '11/4/2023', 'chocolate', 'lunch', 46, 'total carbohydrate', '3/2/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (47, '9/1/2023', 'apples', 'dinner', 47, 'added sugars', '8/19/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (48, '5/24/2024', 'ice cream', 'snack', 48, 'dietary fiber', '5/18/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (49, '3/4/2024', 'bananas', 'breakfast', 49, 'cholesterol', '6/1/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (50, '12/27/2023', 'ice cream', 'dinner', 50, 'and certain vitamins and minerals', '9/15/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (51, '7/20/2024', 'pasta', 'dinner', 51, 'sodium', '4/22/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (52, '5/17/2024', 'apples', 'lunch', 52, 'dietary fiber', '2/15/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (53, '12/11/2023', 'pasta', 'breakfast', 53, 'cholesterol', '12/16/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (54, '7/12/2024', 'apples', 'snack', 54, 'sodium', '7/21/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (55, '6/13/2024', 'bananas', 'snack', 55, 'trans fat', '10/2/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (56, '8/25/2024', 'chocolate', 'dinner', 56, 'protein', '2/5/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (57, '6/13/2024', 'apples', 'snack', 57, 'cholesterol', '9/19/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (58, '9/2/2023', 'apples', 'dinner', 58, 'saturated fat', '3/8/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (59, '9/19/2023', 'carrots', 'snack', 59, 'dietary fiber', '9/10/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (60, '7/10/2024', 'apples', 'dinner', 60, 'protein', '8/4/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (61, '9/27/2023', 'pizza', 'breakfast', 61, 'and certain vitamins and minerals', '8/5/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (62, '6/1/2024', 'chocolate', 'lunch', 62, 'and certain vitamins and minerals', '5/29/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (63, '3/13/2024', 'bananas', 'snack', 63, 'dietary fiber', '1/5/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (64, '10/18/2023', 'carrots', 'dinner', 64, 'total sugars', '7/20/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (65, '9/4/2023', 'carrots', 'dinner', 65, 'protein', '11/10/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (66, '8/3/2023', 'apples', 'dinner', 66, 'total sugars', '5/9/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (67, '2/12/2024', 'bananas', 'snack', 67, 'dietary fiber', '8/4/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (68, '8/1/2024', 'chocolate', 'dinner', 68, 'fat', '9/16/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (69, '2/22/2024', 'bananas', 'dinner', 69, 'saturated fat', '10/6/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (70, '7/1/2024', 'pizza', 'breakfast', 70, 'total sugars', '1/20/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (71, '1/29/2024', 'chocolate', 'breakfast', 71, 'saturated fat', '3/16/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (72, '8/9/2024', 'carrots', 'dinner', 72, 'total sugars', '8/27/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (73, '4/22/2024', 'carrots', 'lunch', 73, 'total sugars', '7/28/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (74, '10/3/2023', 'apples', 'breakfast', 74, 'and certain vitamins and minerals', '7/7/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (75, '11/10/2023', 'pasta', 'breakfast', 75, 'total sugars', '11/22/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (76, '11/18/2023', 'pizza', 'dinner', 76, 'sodium', '3/12/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (77, '5/9/2024', 'pasta', 'breakfast', 77, 'and certain vitamins and minerals', '8/10/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (78, '8/18/2023', 'carrots', 'dinner', 78, 'total carbohydrate', '4/11/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (79, '5/19/2024', 'bananas', 'lunch', 79, 'total sugars', '12/11/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (80, '3/27/2024', 'ice cream', 'breakfast', 80, 'added sugars', '7/4/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (81, '10/1/2023', 'bananas', 'breakfast', 81, 'total carbohydrate', '6/21/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (82, '3/6/2024', 'bananas', 'dinner', 82, 'dietary fiber', '3/18/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (83, '3/31/2024', 'chocolate', 'dinner', 83, 'protein', '1/7/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (84, '4/16/2024', 'carrots', 'breakfast', 84, 'cholesterol', '10/2/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (85, '8/22/2024', 'pasta', 'snack', 85, 'added sugars', '6/17/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (86, '2/5/2024', 'chocolate', 'lunch', 86, 'fat', '11/4/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (87, '11/8/2023', 'chocolate', 'dinner', 87, 'and certain vitamins and minerals', '3/3/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (88, '8/13/2023', 'carrots', 'snack', 88, 'added sugars', '4/14/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (89, '8/13/2023', 'chocolate', 'dinner', 89, 'fat', '2/13/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (90, '4/6/2024', 'ice cream', 'breakfast', 90, 'trans fat', '10/2/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (91, '1/26/2024', 'ice cream', 'dinner', 91, 'protein', '12/31/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (92, '5/3/2024', 'chocolate', 'lunch', 92, 'trans fat', '8/28/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (93, '9/7/2023', 'carrots', 'dinner', 93, 'cholesterol', '12/18/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (94, '5/16/2024', 'bananas', 'snack', 94, 'sodium', '5/9/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (95, '8/12/2023', 'apples', 'dinner', 95, 'cholesterol', '10/19/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (96, '8/9/2023', 'carrots', 'lunch', 96, 'cholesterol', '8/30/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (97, '12/8/2023', 'pizza', 'dinner', 97, 'saturated fat', '8/9/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (98, '4/29/2024', 'pasta', 'dinner', 98, 'and certain vitamins and minerals', '1/12/2024');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (99, '8/7/2024', 'carrots', 'dinner', 99, 'total sugars', '8/7/2023');
insert into Meal_Plan (client_id, created_at, ingredients, description, meal_plan_id, nutrition_info, updated_at) values (100, '3/29/2024', 'bananas', 'breakfast', 100, 'sodium', '8/4/2023');
